// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fdb542c3-0e3e-4cdf-ba48-b898835a4f81",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KqjJ6h2ek",
    "aws_user_pools_web_client_id": "29jqck565fq01mok2nhcl6lk34",
    "aws_appsync_graphqlEndpoint": "https://ojr6mlcsvnhtxfnagroxb6pbry.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
